#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 136
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 72
#define ALIAS_COUNT 0
#define TOKEN_COUNT 42
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_COLON = 1,
  anon_sym_SEMI = 2,
  anon_sym_COMMA = 3,
  anon_sym_LBRACK = 4,
  anon_sym_RBRACK = 5,
  sym_open_bracket = 6,
  sym_close_bracket = 7,
  sym_open_arrow = 8,
  sym_close_arrow = 9,
  anon_sym_SLASH = 10,
  anon_sym_DOT = 11,
  sym_identifier = 12,
  anon_sym_SQUOTE = 13,
  anon_sym_DQUOTE = 14,
  sym_single_string_contents = 15,
  sym_double_string_contents = 16,
  sym_oct = 17,
  sym_hex = 18,
  anon_sym_BSLASHa = 19,
  anon_sym_BSLASHb = 20,
  anon_sym_BSLASHf = 21,
  anon_sym_BSLASHn = 22,
  anon_sym_BSLASHr = 23,
  anon_sym_BSLASHt = 24,
  anon_sym_BSLASHv = 25,
  anon_sym_BSLASH_QMARK = 26,
  anon_sym_BSLASH_DQUOTE = 27,
  anon_sym_BSLASH_SQUOTE = 28,
  anon_sym_BSLASH = 29,
  anon_sym_BSLASHx = 30,
  anon_sym_BSLASHu = 31,
  anon_sym_BSLASHU000 = 32,
  anon_sym_BSLASHU010 = 33,
  anon_sym_0 = 34,
  aux_sym_dec_int_token1 = 35,
  aux_sym_dec_int_token2 = 36,
  anon_sym_X = 37,
  anon_sym_x = 38,
  aux_sym_exp_token1 = 39,
  anon_sym_POUND = 40,
  aux_sym_comment_token1 = 41,
  sym_source_file = 42,
  sym_field = 43,
  sym_message_field = 44,
  sym_message_value = 45,
  sym_message_list = 46,
  sym_scalar_field = 47,
  sym_field_name = 48,
  sym_extension_name = 49,
  sym_any_name = 50,
  sym_type_name = 51,
  sym_domain = 52,
  sym_scalar_value = 53,
  sym_scalar_list = 54,
  sym_string = 55,
  sym_single_string = 56,
  sym_double_string = 57,
  sym_string_escape = 58,
  sym_number = 59,
  sym_dec_int = 60,
  sym_oct_int = 61,
  sym_hex_int = 62,
  sym_float = 63,
  sym_exp = 64,
  sym_comment = 65,
  aux_sym_source_file_repeat1 = 66,
  aux_sym_message_list_repeat1 = 67,
  aux_sym_type_name_repeat1 = 68,
  aux_sym_scalar_list_repeat1 = 69,
  aux_sym_single_string_repeat1 = 70,
  aux_sym_double_string_repeat1 = 71,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COLON] = ":",
  [anon_sym_SEMI] = ";",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_open_bracket] = "open_bracket",
  [sym_close_bracket] = "close_bracket",
  [sym_open_arrow] = "open_arrow",
  [sym_close_arrow] = "close_arrow",
  [anon_sym_SLASH] = "/",
  [anon_sym_DOT] = ".",
  [sym_identifier] = "identifier",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_DQUOTE] = "\"",
  [sym_single_string_contents] = "single_string_contents",
  [sym_double_string_contents] = "double_string_contents",
  [sym_oct] = "oct",
  [sym_hex] = "hex",
  [anon_sym_BSLASHa] = "\\a",
  [anon_sym_BSLASHb] = "\\b",
  [anon_sym_BSLASHf] = "\\f",
  [anon_sym_BSLASHn] = "\\n",
  [anon_sym_BSLASHr] = "\\r",
  [anon_sym_BSLASHt] = "\\t",
  [anon_sym_BSLASHv] = "\\v",
  [anon_sym_BSLASH_QMARK] = "\\\?",
  [anon_sym_BSLASH_DQUOTE] = "\\\"",
  [anon_sym_BSLASH_SQUOTE] = "\\'",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_BSLASHx] = "\\x",
  [anon_sym_BSLASHu] = "\\u",
  [anon_sym_BSLASHU000] = "\\U000",
  [anon_sym_BSLASHU010] = "\\U010",
  [anon_sym_0] = "0",
  [aux_sym_dec_int_token1] = "dec_int_token1",
  [aux_sym_dec_int_token2] = "dec_int_token2",
  [anon_sym_X] = "X",
  [anon_sym_x] = "x",
  [aux_sym_exp_token1] = "exp_token1",
  [anon_sym_POUND] = "#",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_source_file] = "source_file",
  [sym_field] = "field",
  [sym_message_field] = "message_field",
  [sym_message_value] = "message_value",
  [sym_message_list] = "message_list",
  [sym_scalar_field] = "scalar_field",
  [sym_field_name] = "field_name",
  [sym_extension_name] = "extension_name",
  [sym_any_name] = "any_name",
  [sym_type_name] = "type_name",
  [sym_domain] = "domain",
  [sym_scalar_value] = "scalar_value",
  [sym_scalar_list] = "scalar_list",
  [sym_string] = "string",
  [sym_single_string] = "single_string",
  [sym_double_string] = "double_string",
  [sym_string_escape] = "string_escape",
  [sym_number] = "number",
  [sym_dec_int] = "dec_int",
  [sym_oct_int] = "oct_int",
  [sym_hex_int] = "hex_int",
  [sym_float] = "float",
  [sym_exp] = "exp",
  [sym_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_message_list_repeat1] = "message_list_repeat1",
  [aux_sym_type_name_repeat1] = "type_name_repeat1",
  [aux_sym_scalar_list_repeat1] = "scalar_list_repeat1",
  [aux_sym_single_string_repeat1] = "single_string_repeat1",
  [aux_sym_double_string_repeat1] = "double_string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_open_bracket] = sym_open_bracket,
  [sym_close_bracket] = sym_close_bracket,
  [sym_open_arrow] = sym_open_arrow,
  [sym_close_arrow] = sym_close_arrow,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_identifier] = sym_identifier,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_single_string_contents] = sym_single_string_contents,
  [sym_double_string_contents] = sym_double_string_contents,
  [sym_oct] = sym_oct,
  [sym_hex] = sym_hex,
  [anon_sym_BSLASHa] = anon_sym_BSLASHa,
  [anon_sym_BSLASHb] = anon_sym_BSLASHb,
  [anon_sym_BSLASHf] = anon_sym_BSLASHf,
  [anon_sym_BSLASHn] = anon_sym_BSLASHn,
  [anon_sym_BSLASHr] = anon_sym_BSLASHr,
  [anon_sym_BSLASHt] = anon_sym_BSLASHt,
  [anon_sym_BSLASHv] = anon_sym_BSLASHv,
  [anon_sym_BSLASH_QMARK] = anon_sym_BSLASH_QMARK,
  [anon_sym_BSLASH_DQUOTE] = anon_sym_BSLASH_DQUOTE,
  [anon_sym_BSLASH_SQUOTE] = anon_sym_BSLASH_SQUOTE,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_BSLASHx] = anon_sym_BSLASHx,
  [anon_sym_BSLASHu] = anon_sym_BSLASHu,
  [anon_sym_BSLASHU000] = anon_sym_BSLASHU000,
  [anon_sym_BSLASHU010] = anon_sym_BSLASHU010,
  [anon_sym_0] = anon_sym_0,
  [aux_sym_dec_int_token1] = aux_sym_dec_int_token1,
  [aux_sym_dec_int_token2] = aux_sym_dec_int_token2,
  [anon_sym_X] = anon_sym_X,
  [anon_sym_x] = anon_sym_x,
  [aux_sym_exp_token1] = aux_sym_exp_token1,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_source_file] = sym_source_file,
  [sym_field] = sym_field,
  [sym_message_field] = sym_message_field,
  [sym_message_value] = sym_message_value,
  [sym_message_list] = sym_message_list,
  [sym_scalar_field] = sym_scalar_field,
  [sym_field_name] = sym_field_name,
  [sym_extension_name] = sym_extension_name,
  [sym_any_name] = sym_any_name,
  [sym_type_name] = sym_type_name,
  [sym_domain] = sym_domain,
  [sym_scalar_value] = sym_scalar_value,
  [sym_scalar_list] = sym_scalar_list,
  [sym_string] = sym_string,
  [sym_single_string] = sym_single_string,
  [sym_double_string] = sym_double_string,
  [sym_string_escape] = sym_string_escape,
  [sym_number] = sym_number,
  [sym_dec_int] = sym_dec_int,
  [sym_oct_int] = sym_oct_int,
  [sym_hex_int] = sym_hex_int,
  [sym_float] = sym_float,
  [sym_exp] = sym_exp,
  [sym_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_message_list_repeat1] = aux_sym_message_list_repeat1,
  [aux_sym_type_name_repeat1] = aux_sym_type_name_repeat1,
  [aux_sym_scalar_list_repeat1] = aux_sym_scalar_list_repeat1,
  [aux_sym_single_string_repeat1] = aux_sym_single_string_repeat1,
  [aux_sym_double_string_repeat1] = aux_sym_double_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_open_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_close_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_open_arrow] = {
    .visible = true,
    .named = true,
  },
  [sym_close_arrow] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_single_string_contents] = {
    .visible = true,
    .named = true,
  },
  [sym_double_string_contents] = {
    .visible = true,
    .named = true,
  },
  [sym_oct] = {
    .visible = true,
    .named = true,
  },
  [sym_hex] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BSLASHa] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHb] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHf] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHr] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHt] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHv] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHx] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHu] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHU000] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHU010] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_0] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_dec_int_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dec_int_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_X] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_x] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_exp_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_message_field] = {
    .visible = true,
    .named = true,
  },
  [sym_message_value] = {
    .visible = true,
    .named = true,
  },
  [sym_message_list] = {
    .visible = true,
    .named = true,
  },
  [sym_scalar_field] = {
    .visible = true,
    .named = true,
  },
  [sym_field_name] = {
    .visible = true,
    .named = true,
  },
  [sym_extension_name] = {
    .visible = true,
    .named = true,
  },
  [sym_any_name] = {
    .visible = true,
    .named = true,
  },
  [sym_type_name] = {
    .visible = true,
    .named = true,
  },
  [sym_domain] = {
    .visible = true,
    .named = true,
  },
  [sym_scalar_value] = {
    .visible = true,
    .named = true,
  },
  [sym_scalar_list] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_single_string] = {
    .visible = true,
    .named = true,
  },
  [sym_double_string] = {
    .visible = true,
    .named = true,
  },
  [sym_string_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_dec_int] = {
    .visible = true,
    .named = true,
  },
  [sym_oct_int] = {
    .visible = true,
    .named = true,
  },
  [sym_hex_int] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_exp] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_message_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_name_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_scalar_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_single_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_double_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 9,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 11,
  [15] = 12,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 18,
  [20] = 20,
  [21] = 21,
  [22] = 21,
  [23] = 16,
  [24] = 24,
  [25] = 17,
  [26] = 26,
  [27] = 26,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 29,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 35,
  [75] = 36,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 41,
  [81] = 81,
  [82] = 39,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 38,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 52,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 107,
  [120] = 120,
  [121] = 121,
  [122] = 114,
  [123] = 110,
  [124] = 109,
  [125] = 106,
  [126] = 111,
  [127] = 118,
  [128] = 105,
  [129] = 115,
  [130] = 103,
  [131] = 121,
  [132] = 113,
  [133] = 108,
  [134] = 116,
  [135] = 135,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(17);
      if (lookahead == '"') ADVANCE(32);
      if (lookahead == '#') ADVANCE(65);
      if (lookahead == '\'') ADVANCE(31);
      if (lookahead == ',') ADVANCE(20);
      if (lookahead == '.') ADVANCE(28);
      if (lookahead == '/') ADVANCE(27);
      if (lookahead == '0') ADVANCE(56);
      if (lookahead == ':') ADVANCE(18);
      if (lookahead == ';') ADVANCE(19);
      if (lookahead == '<') ADVANCE(25);
      if (lookahead == '>') ADVANCE(26);
      if (lookahead == 'X') ADVANCE(60);
      if (lookahead == '[') ADVANCE(21);
      if (lookahead == '\\') ADVANCE(51);
      if (lookahead == ']') ADVANCE(22);
      if (lookahead == 'x') ADVANCE(62);
      if (lookahead == '{') ADVANCE(23);
      if (lookahead == '}') ADVANCE(24);
      if (lookahead == '8' ||
          lookahead == '9') ADVANCE(40);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('1' <= lookahead && lookahead <= '7')) ADVANCE(39);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(30);
      if (('G' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1)
      if (lookahead == '"') ADVANCE(32);
      if (lookahead == '#') ADVANCE(66);
      if (lookahead == '\\') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(38);
      if (lookahead != 0) ADVANCE(38);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2)
      if (lookahead == '#') ADVANCE(67);
      if (lookahead == '\'') ADVANCE(31);
      if (lookahead == '\\') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(35);
      if (lookahead != 0) ADVANCE(35);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(3)
      if (lookahead == '#') ADVANCE(67);
      if (lookahead == '\'') ADVANCE(31);
      if (lookahead == '\\') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(35);
      if (lookahead != 0) ADVANCE(35);
      END_STATE();
    case 4:
      if (lookahead == '\n') SKIP(4)
      if (lookahead == '"') ADVANCE(32);
      if (lookahead == '#') ADVANCE(66);
      if (lookahead == '\\') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(38);
      if (lookahead != 0) ADVANCE(38);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(65);
      if (lookahead == ',') ADVANCE(20);
      if (lookahead == '.') ADVANCE(28);
      if (lookahead == 'X') ADVANCE(59);
      if (lookahead == ']') ADVANCE(22);
      if (lookahead == 'x') ADVANCE(61);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(64);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5)
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(39);
      END_STATE();
    case 6:
      if (lookahead == '#') ADVANCE(65);
      if (lookahead == ',') ADVANCE(20);
      if (lookahead == '.') ADVANCE(28);
      if (lookahead == ']') ADVANCE(22);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(64);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(6)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      END_STATE();
    case 7:
      if (lookahead == '#') ADVANCE(65);
      if (lookahead == ',') ADVANCE(20);
      if (lookahead == ']') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(7)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(40);
      END_STATE();
    case 8:
      if (lookahead == '0') ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == '0') ADVANCE(54);
      END_STATE();
    case 10:
      if (lookahead == '0') ADVANCE(55);
      END_STATE();
    case 11:
      if (lookahead == '0') ADVANCE(9);
      if (lookahead == '1') ADVANCE(10);
      END_STATE();
    case 12:
      if (eof) ADVANCE(17);
      if (lookahead == '"') ADVANCE(32);
      if (lookahead == '#') ADVANCE(65);
      if (lookahead == '\'') ADVANCE(31);
      if (lookahead == ',') ADVANCE(20);
      if (lookahead == '.') ADVANCE(28);
      if (lookahead == '/') ADVANCE(27);
      if (lookahead == '0') ADVANCE(56);
      if (lookahead == ';') ADVANCE(19);
      if (lookahead == '<') ADVANCE(25);
      if (lookahead == '>') ADVANCE(26);
      if (lookahead == '[') ADVANCE(21);
      if (lookahead == ']') ADVANCE(22);
      if (lookahead == '{') ADVANCE(23);
      if (lookahead == '}') ADVANCE(24);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(29);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(12)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(57);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 13:
      if (eof) ADVANCE(17);
      if (lookahead == '#') ADVANCE(65);
      if (lookahead == ',') ADVANCE(20);
      if (lookahead == '.') ADVANCE(28);
      if (lookahead == ';') ADVANCE(19);
      if (lookahead == '>') ADVANCE(26);
      if (lookahead == 'X') ADVANCE(60);
      if (lookahead == '[') ADVANCE(21);
      if (lookahead == 'x') ADVANCE(62);
      if (lookahead == '}') ADVANCE(24);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(29);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(13)
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(39);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 14:
      if (eof) ADVANCE(17);
      if (lookahead == '#') ADVANCE(65);
      if (lookahead == ',') ADVANCE(20);
      if (lookahead == '.') ADVANCE(28);
      if (lookahead == ';') ADVANCE(19);
      if (lookahead == '>') ADVANCE(26);
      if (lookahead == '[') ADVANCE(21);
      if (lookahead == '}') ADVANCE(24);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(29);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(14)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 15:
      if (eof) ADVANCE(17);
      if (lookahead == '#') ADVANCE(65);
      if (lookahead == ',') ADVANCE(20);
      if (lookahead == ';') ADVANCE(19);
      if (lookahead == '>') ADVANCE(26);
      if (lookahead == '[') ADVANCE(21);
      if (lookahead == ']') ADVANCE(22);
      if (lookahead == '}') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(15)
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(39);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 16:
      if (eof) ADVANCE(17);
      if (lookahead == '#') ADVANCE(65);
      if (lookahead == ',') ADVANCE(20);
      if (lookahead == ';') ADVANCE(19);
      if (lookahead == '>') ADVANCE(26);
      if (lookahead == '[') ADVANCE(21);
      if (lookahead == '}') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(16)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(30);
      if (('G' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_open_bracket);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_close_bracket);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_open_arrow);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_close_arrow);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_single_string_contents);
      if (lookahead == '#') ADVANCE(67);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(35);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_single_string_contents);
      if (lookahead == '#') ADVANCE(67);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(35);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_single_string_contents);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_double_string_contents);
      if (lookahead == '#') ADVANCE(66);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(38);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_double_string_contents);
      if (lookahead == '#') ADVANCE(66);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(38);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_double_string_contents);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_oct);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_hex);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_BSLASHa);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_BSLASHb);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_BSLASHf);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_BSLASHn);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_BSLASHr);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_BSLASHt);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_BSLASHv);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_BSLASH_QMARK);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_BSLASH_DQUOTE);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_BSLASH_SQUOTE);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      if (lookahead == '"') ADVANCE(49);
      if (lookahead == '\'') ADVANCE(50);
      if (lookahead == '?') ADVANCE(48);
      if (lookahead == 'U') ADVANCE(8);
      if (lookahead == 'a') ADVANCE(41);
      if (lookahead == 'b') ADVANCE(42);
      if (lookahead == 'f') ADVANCE(43);
      if (lookahead == 'n') ADVANCE(44);
      if (lookahead == 'r') ADVANCE(45);
      if (lookahead == 't') ADVANCE(46);
      if (lookahead == 'u') ADVANCE(53);
      if (lookahead == 'v') ADVANCE(47);
      if (lookahead == 'x') ADVANCE(52);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_BSLASHx);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_BSLASHu);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_BSLASHU000);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_BSLASHU010);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_0);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_dec_int_token1);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_dec_int_token2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_X);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_X);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_x);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_x);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_exp_token1);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_exp_token1);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(63);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(38);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(35);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '#') ADVANCE(68);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(69);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 12},
  [2] = {.lex_state = 12},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 12},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 12},
  [29] = {.lex_state = 13},
  [30] = {.lex_state = 12},
  [31] = {.lex_state = 12},
  [32] = {.lex_state = 12},
  [33] = {.lex_state = 12},
  [34] = {.lex_state = 12},
  [35] = {.lex_state = 12},
  [36] = {.lex_state = 14},
  [37] = {.lex_state = 12},
  [38] = {.lex_state = 12},
  [39] = {.lex_state = 12},
  [40] = {.lex_state = 15},
  [41] = {.lex_state = 12},
  [42] = {.lex_state = 12},
  [43] = {.lex_state = 12},
  [44] = {.lex_state = 12},
  [45] = {.lex_state = 12},
  [46] = {.lex_state = 12},
  [47] = {.lex_state = 12},
  [48] = {.lex_state = 12},
  [49] = {.lex_state = 12},
  [50] = {.lex_state = 12},
  [51] = {.lex_state = 12},
  [52] = {.lex_state = 16},
  [53] = {.lex_state = 12},
  [54] = {.lex_state = 12},
  [55] = {.lex_state = 12},
  [56] = {.lex_state = 12},
  [57] = {.lex_state = 12},
  [58] = {.lex_state = 12},
  [59] = {.lex_state = 12},
  [60] = {.lex_state = 12},
  [61] = {.lex_state = 5},
  [62] = {.lex_state = 12},
  [63] = {.lex_state = 12},
  [64] = {.lex_state = 12},
  [65] = {.lex_state = 12},
  [66] = {.lex_state = 12},
  [67] = {.lex_state = 12},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 12},
  [70] = {.lex_state = 12},
  [71] = {.lex_state = 12},
  [72] = {.lex_state = 12},
  [73] = {.lex_state = 12},
  [74] = {.lex_state = 5},
  [75] = {.lex_state = 6},
  [76] = {.lex_state = 12},
  [77] = {.lex_state = 12},
  [78] = {.lex_state = 12},
  [79] = {.lex_state = 12},
  [80] = {.lex_state = 5},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 5},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 12},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 5},
  [87] = {.lex_state = 12},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 12},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 7},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 12},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 7},
  [104] = {.lex_state = 69},
  [105] = {.lex_state = 7},
  [106] = {.lex_state = 7},
  [107] = {.lex_state = 7},
  [108] = {.lex_state = 7},
  [109] = {.lex_state = 7},
  [110] = {.lex_state = 13},
  [111] = {.lex_state = 14},
  [112] = {.lex_state = 14},
  [113] = {.lex_state = 7},
  [114] = {.lex_state = 14},
  [115] = {.lex_state = 7},
  [116] = {.lex_state = 7},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 7},
  [119] = {.lex_state = 7},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 7},
  [122] = {.lex_state = 14},
  [123] = {.lex_state = 13},
  [124] = {.lex_state = 7},
  [125] = {.lex_state = 7},
  [126] = {.lex_state = 14},
  [127] = {.lex_state = 7},
  [128] = {.lex_state = 7},
  [129] = {.lex_state = 7},
  [130] = {.lex_state = 7},
  [131] = {.lex_state = 7},
  [132] = {.lex_state = 7},
  [133] = {.lex_state = 7},
  [134] = {.lex_state = 7},
  [135] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_open_bracket] = ACTIONS(1),
    [sym_close_bracket] = ACTIONS(1),
    [sym_open_arrow] = ACTIONS(1),
    [sym_close_arrow] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_oct] = ACTIONS(1),
    [sym_hex] = ACTIONS(1),
    [anon_sym_BSLASHa] = ACTIONS(1),
    [anon_sym_BSLASHb] = ACTIONS(1),
    [anon_sym_BSLASHf] = ACTIONS(1),
    [anon_sym_BSLASHn] = ACTIONS(1),
    [anon_sym_BSLASHr] = ACTIONS(1),
    [anon_sym_BSLASHt] = ACTIONS(1),
    [anon_sym_BSLASHv] = ACTIONS(1),
    [anon_sym_BSLASH_QMARK] = ACTIONS(1),
    [anon_sym_BSLASH_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH_SQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_BSLASHx] = ACTIONS(1),
    [anon_sym_BSLASHu] = ACTIONS(1),
    [anon_sym_BSLASHU000] = ACTIONS(1),
    [anon_sym_BSLASHU010] = ACTIONS(1),
    [anon_sym_0] = ACTIONS(1),
    [aux_sym_dec_int_token1] = ACTIONS(1),
    [anon_sym_X] = ACTIONS(1),
    [anon_sym_x] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(120),
    [sym_field] = STATE(78),
    [sym_message_field] = STATE(77),
    [sym_scalar_field] = STATE(77),
    [sym_field_name] = STATE(68),
    [sym_extension_name] = STATE(81),
    [sym_any_name] = STATE(81),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(32),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 16,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_open_bracket,
    ACTIONS(15), 1,
      sym_open_arrow,
    ACTIONS(17), 1,
      anon_sym_DOT,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      anon_sym_0,
    ACTIONS(25), 1,
      aux_sym_dec_int_token1,
    STATE(2), 1,
      sym_comment,
    STATE(35), 1,
      sym_dec_int,
    STATE(51), 2,
      sym_single_string,
      sym_double_string,
    STATE(56), 2,
      sym_string,
      sym_number,
    STATE(63), 2,
      sym_message_value,
      sym_message_list,
    STATE(64), 2,
      sym_scalar_value,
      sym_scalar_list,
    STATE(50), 3,
      sym_oct_int,
      sym_hex_int,
      sym_float,
  [55] = 10,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      sym_double_string_contents,
    ACTIONS(35), 1,
      anon_sym_BSLASH,
    ACTIONS(38), 1,
      anon_sym_BSLASHx,
    ACTIONS(44), 1,
      anon_sym_BSLASHU000,
    ACTIONS(47), 1,
      anon_sym_POUND,
    STATE(24), 1,
      sym_string_escape,
    ACTIONS(41), 2,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU010,
    STATE(3), 2,
      sym_comment,
      aux_sym_double_string_repeat1,
    ACTIONS(32), 10,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
  [97] = 11,
    ACTIONS(47), 1,
      anon_sym_POUND,
    ACTIONS(49), 1,
      anon_sym_DQUOTE,
    ACTIONS(51), 1,
      sym_double_string_contents,
    ACTIONS(55), 1,
      anon_sym_BSLASH,
    ACTIONS(57), 1,
      anon_sym_BSLASHx,
    ACTIONS(61), 1,
      anon_sym_BSLASHU000,
    STATE(4), 1,
      sym_comment,
    STATE(6), 1,
      aux_sym_double_string_repeat1,
    STATE(24), 1,
      sym_string_escape,
    ACTIONS(59), 2,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU010,
    ACTIONS(53), 10,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
  [141] = 11,
    ACTIONS(47), 1,
      anon_sym_POUND,
    ACTIONS(63), 1,
      anon_sym_SQUOTE,
    ACTIONS(65), 1,
      sym_single_string_contents,
    ACTIONS(69), 1,
      anon_sym_BSLASH,
    ACTIONS(71), 1,
      anon_sym_BSLASHx,
    ACTIONS(75), 1,
      anon_sym_BSLASHU000,
    STATE(5), 1,
      sym_comment,
    STATE(7), 1,
      aux_sym_single_string_repeat1,
    STATE(20), 1,
      sym_string_escape,
    ACTIONS(73), 2,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU010,
    ACTIONS(67), 10,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
  [185] = 11,
    ACTIONS(47), 1,
      anon_sym_POUND,
    ACTIONS(51), 1,
      sym_double_string_contents,
    ACTIONS(55), 1,
      anon_sym_BSLASH,
    ACTIONS(57), 1,
      anon_sym_BSLASHx,
    ACTIONS(61), 1,
      anon_sym_BSLASHU000,
    ACTIONS(77), 1,
      anon_sym_DQUOTE,
    STATE(3), 1,
      aux_sym_double_string_repeat1,
    STATE(6), 1,
      sym_comment,
    STATE(24), 1,
      sym_string_escape,
    ACTIONS(59), 2,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU010,
    ACTIONS(53), 10,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
  [229] = 11,
    ACTIONS(47), 1,
      anon_sym_POUND,
    ACTIONS(65), 1,
      sym_single_string_contents,
    ACTIONS(69), 1,
      anon_sym_BSLASH,
    ACTIONS(71), 1,
      anon_sym_BSLASHx,
    ACTIONS(75), 1,
      anon_sym_BSLASHU000,
    ACTIONS(79), 1,
      anon_sym_SQUOTE,
    STATE(7), 1,
      sym_comment,
    STATE(8), 1,
      aux_sym_single_string_repeat1,
    STATE(20), 1,
      sym_string_escape,
    ACTIONS(73), 2,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU010,
    ACTIONS(67), 10,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
  [273] = 10,
    ACTIONS(47), 1,
      anon_sym_POUND,
    ACTIONS(81), 1,
      anon_sym_SQUOTE,
    ACTIONS(83), 1,
      sym_single_string_contents,
    ACTIONS(89), 1,
      anon_sym_BSLASH,
    ACTIONS(92), 1,
      anon_sym_BSLASHx,
    ACTIONS(98), 1,
      anon_sym_BSLASHU000,
    STATE(20), 1,
      sym_string_escape,
    ACTIONS(95), 2,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU010,
    STATE(8), 2,
      sym_comment,
      aux_sym_single_string_repeat1,
    ACTIONS(86), 10,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
  [315] = 4,
    ACTIONS(47), 1,
      anon_sym_POUND,
    ACTIONS(103), 1,
      sym_oct,
    STATE(9), 1,
      sym_comment,
    ACTIONS(101), 17,
      anon_sym_SQUOTE,
      sym_single_string_contents,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHx,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU000,
      anon_sym_BSLASHU010,
  [344] = 4,
    ACTIONS(47), 1,
      anon_sym_POUND,
    ACTIONS(105), 1,
      sym_oct,
    STATE(10), 1,
      sym_comment,
    ACTIONS(101), 17,
      anon_sym_DQUOTE,
      sym_double_string_contents,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHx,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU000,
      anon_sym_BSLASHU010,
  [373] = 4,
    ACTIONS(47), 1,
      anon_sym_POUND,
    ACTIONS(107), 1,
      sym_hex,
    STATE(11), 1,
      sym_comment,
    ACTIONS(101), 17,
      anon_sym_SQUOTE,
      sym_single_string_contents,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHx,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU000,
      anon_sym_BSLASHU010,
  [402] = 4,
    ACTIONS(47), 1,
      anon_sym_POUND,
    ACTIONS(111), 1,
      sym_oct,
    STATE(12), 1,
      sym_comment,
    ACTIONS(109), 17,
      anon_sym_SQUOTE,
      sym_single_string_contents,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHx,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU000,
      anon_sym_BSLASHU010,
  [431] = 16,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(13), 1,
      sym_open_bracket,
    ACTIONS(15), 1,
      sym_open_arrow,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(113), 1,
      anon_sym_RBRACK,
    ACTIONS(115), 1,
      anon_sym_DOT,
    ACTIONS(117), 1,
      anon_sym_0,
    ACTIONS(119), 1,
      aux_sym_dec_int_token1,
    STATE(13), 1,
      sym_comment,
    STATE(74), 1,
      sym_dec_int,
    STATE(94), 1,
      sym_message_value,
    STATE(95), 1,
      sym_scalar_value,
    STATE(51), 2,
      sym_single_string,
      sym_double_string,
    STATE(56), 2,
      sym_string,
      sym_number,
    STATE(50), 3,
      sym_oct_int,
      sym_hex_int,
      sym_float,
  [484] = 4,
    ACTIONS(47), 1,
      anon_sym_POUND,
    ACTIONS(121), 1,
      sym_hex,
    STATE(14), 1,
      sym_comment,
    ACTIONS(101), 17,
      anon_sym_DQUOTE,
      sym_double_string_contents,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHx,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU000,
      anon_sym_BSLASHU010,
  [513] = 4,
    ACTIONS(47), 1,
      anon_sym_POUND,
    ACTIONS(123), 1,
      sym_oct,
    STATE(15), 1,
      sym_comment,
    ACTIONS(109), 17,
      anon_sym_DQUOTE,
      sym_double_string_contents,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHx,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU000,
      anon_sym_BSLASHU010,
  [542] = 3,
    ACTIONS(47), 1,
      anon_sym_POUND,
    STATE(16), 1,
      sym_comment,
    ACTIONS(109), 17,
      anon_sym_SQUOTE,
      sym_single_string_contents,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHx,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU000,
      anon_sym_BSLASHU010,
  [568] = 3,
    ACTIONS(47), 1,
      anon_sym_POUND,
    STATE(17), 1,
      sym_comment,
    ACTIONS(125), 17,
      anon_sym_SQUOTE,
      sym_single_string_contents,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHx,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU000,
      anon_sym_BSLASHU010,
  [594] = 3,
    ACTIONS(47), 1,
      anon_sym_POUND,
    STATE(18), 1,
      sym_comment,
    ACTIONS(127), 17,
      anon_sym_DQUOTE,
      sym_double_string_contents,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHx,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU000,
      anon_sym_BSLASHU010,
  [620] = 3,
    ACTIONS(47), 1,
      anon_sym_POUND,
    STATE(19), 1,
      sym_comment,
    ACTIONS(127), 17,
      anon_sym_SQUOTE,
      sym_single_string_contents,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHx,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU000,
      anon_sym_BSLASHU010,
  [646] = 3,
    ACTIONS(47), 1,
      anon_sym_POUND,
    STATE(20), 1,
      sym_comment,
    ACTIONS(129), 17,
      anon_sym_SQUOTE,
      sym_single_string_contents,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHx,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU000,
      anon_sym_BSLASHU010,
  [672] = 3,
    ACTIONS(47), 1,
      anon_sym_POUND,
    STATE(21), 1,
      sym_comment,
    ACTIONS(131), 17,
      anon_sym_DQUOTE,
      sym_double_string_contents,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHx,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU000,
      anon_sym_BSLASHU010,
  [698] = 3,
    ACTIONS(47), 1,
      anon_sym_POUND,
    STATE(22), 1,
      sym_comment,
    ACTIONS(131), 17,
      anon_sym_SQUOTE,
      sym_single_string_contents,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHx,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU000,
      anon_sym_BSLASHU010,
  [724] = 3,
    ACTIONS(47), 1,
      anon_sym_POUND,
    STATE(23), 1,
      sym_comment,
    ACTIONS(109), 17,
      anon_sym_DQUOTE,
      sym_double_string_contents,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHx,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU000,
      anon_sym_BSLASHU010,
  [750] = 3,
    ACTIONS(47), 1,
      anon_sym_POUND,
    STATE(24), 1,
      sym_comment,
    ACTIONS(133), 17,
      anon_sym_DQUOTE,
      sym_double_string_contents,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHx,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU000,
      anon_sym_BSLASHU010,
  [776] = 3,
    ACTIONS(47), 1,
      anon_sym_POUND,
    STATE(25), 1,
      sym_comment,
    ACTIONS(125), 17,
      anon_sym_DQUOTE,
      sym_double_string_contents,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHx,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU000,
      anon_sym_BSLASHU010,
  [802] = 3,
    ACTIONS(47), 1,
      anon_sym_POUND,
    STATE(26), 1,
      sym_comment,
    ACTIONS(135), 17,
      anon_sym_SQUOTE,
      sym_single_string_contents,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHx,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU000,
      anon_sym_BSLASHU010,
  [828] = 3,
    ACTIONS(47), 1,
      anon_sym_POUND,
    STATE(27), 1,
      sym_comment,
    ACTIONS(135), 17,
      anon_sym_DQUOTE,
      sym_double_string_contents,
      anon_sym_BSLASHa,
      anon_sym_BSLASHb,
      anon_sym_BSLASHf,
      anon_sym_BSLASHn,
      anon_sym_BSLASHr,
      anon_sym_BSLASHt,
      anon_sym_BSLASHv,
      anon_sym_BSLASH_QMARK,
      anon_sym_BSLASH_DQUOTE,
      anon_sym_BSLASH_SQUOTE,
      anon_sym_BSLASH,
      anon_sym_BSLASHx,
      anon_sym_BSLASHu,
      anon_sym_BSLASHU000,
      anon_sym_BSLASHU010,
  [854] = 12,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(115), 1,
      anon_sym_DOT,
    ACTIONS(117), 1,
      anon_sym_0,
    ACTIONS(119), 1,
      aux_sym_dec_int_token1,
    STATE(28), 1,
      sym_comment,
    STATE(74), 1,
      sym_dec_int,
    STATE(99), 1,
      sym_scalar_value,
    STATE(51), 2,
      sym_single_string,
      sym_double_string,
    STATE(56), 2,
      sym_string,
      sym_number,
    STATE(50), 3,
      sym_oct_int,
      sym_hex_int,
      sym_float,
  [895] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(141), 1,
      sym_oct,
    STATE(29), 1,
      sym_comment,
    ACTIONS(139), 2,
      sym_identifier,
      aux_sym_exp_token1,
    ACTIONS(143), 2,
      anon_sym_X,
      anon_sym_x,
    ACTIONS(137), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      sym_close_bracket,
      sym_close_arrow,
      anon_sym_DOT,
  [922] = 9,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(147), 1,
      anon_sym_LBRACK,
    ACTIONS(150), 1,
      sym_identifier,
    STATE(68), 1,
      sym_field_name,
    STATE(78), 1,
      sym_field,
    STATE(30), 2,
      sym_comment,
      aux_sym_source_file_repeat1,
    STATE(77), 2,
      sym_message_field,
      sym_scalar_field,
    STATE(81), 2,
      sym_extension_name,
      sym_any_name,
    ACTIONS(145), 3,
      ts_builtin_sym_end,
      sym_close_bracket,
      sym_close_arrow,
  [955] = 10,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(153), 1,
      sym_close_arrow,
    STATE(30), 1,
      aux_sym_source_file_repeat1,
    STATE(31), 1,
      sym_comment,
    STATE(68), 1,
      sym_field_name,
    STATE(78), 1,
      sym_field,
    STATE(77), 2,
      sym_message_field,
      sym_scalar_field,
    STATE(81), 2,
      sym_extension_name,
      sym_any_name,
  [988] = 10,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(155), 1,
      ts_builtin_sym_end,
    STATE(30), 1,
      aux_sym_source_file_repeat1,
    STATE(32), 1,
      sym_comment,
    STATE(68), 1,
      sym_field_name,
    STATE(78), 1,
      sym_field,
    STATE(77), 2,
      sym_message_field,
      sym_scalar_field,
    STATE(81), 2,
      sym_extension_name,
      sym_any_name,
  [1021] = 10,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(157), 1,
      sym_close_bracket,
    STATE(33), 1,
      sym_comment,
    STATE(37), 1,
      aux_sym_source_file_repeat1,
    STATE(68), 1,
      sym_field_name,
    STATE(78), 1,
      sym_field,
    STATE(77), 2,
      sym_message_field,
      sym_scalar_field,
    STATE(81), 2,
      sym_extension_name,
      sym_any_name,
  [1054] = 10,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(157), 1,
      sym_close_arrow,
    STATE(31), 1,
      aux_sym_source_file_repeat1,
    STATE(34), 1,
      sym_comment,
    STATE(68), 1,
      sym_field_name,
    STATE(78), 1,
      sym_field,
    STATE(77), 2,
      sym_message_field,
      sym_scalar_field,
    STATE(81), 2,
      sym_extension_name,
      sym_any_name,
  [1087] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(161), 1,
      anon_sym_DOT,
    ACTIONS(163), 1,
      sym_identifier,
    ACTIONS(165), 1,
      aux_sym_exp_token1,
    STATE(35), 1,
      sym_comment,
    STATE(44), 1,
      sym_exp,
    ACTIONS(159), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      sym_close_bracket,
      sym_close_arrow,
  [1114] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(167), 1,
      aux_sym_dec_int_token2,
    STATE(36), 1,
      sym_comment,
    ACTIONS(139), 2,
      sym_identifier,
      aux_sym_exp_token1,
    ACTIONS(137), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      sym_close_bracket,
      sym_close_arrow,
      anon_sym_DOT,
  [1137] = 10,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(153), 1,
      sym_close_bracket,
    STATE(30), 1,
      aux_sym_source_file_repeat1,
    STATE(37), 1,
      sym_comment,
    STATE(68), 1,
      sym_field_name,
    STATE(78), 1,
      sym_field,
    STATE(77), 2,
      sym_message_field,
      sym_scalar_field,
    STATE(81), 2,
      sym_extension_name,
      sym_any_name,
  [1170] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(165), 1,
      aux_sym_exp_token1,
    ACTIONS(171), 1,
      sym_identifier,
    STATE(38), 1,
      sym_comment,
    STATE(47), 1,
      sym_exp,
    ACTIONS(169), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      sym_close_bracket,
      sym_close_arrow,
  [1194] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(165), 1,
      aux_sym_exp_token1,
    ACTIONS(175), 1,
      sym_identifier,
    STATE(39), 1,
      sym_comment,
    STATE(42), 1,
      sym_exp,
    ACTIONS(173), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      sym_close_bracket,
      sym_close_arrow,
  [1218] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(179), 1,
      sym_oct,
    STATE(40), 1,
      sym_comment,
    ACTIONS(177), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_close_bracket,
      sym_close_arrow,
      sym_identifier,
  [1238] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(41), 1,
      sym_comment,
    ACTIONS(183), 2,
      sym_identifier,
      aux_sym_exp_token1,
    ACTIONS(181), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      sym_close_bracket,
      sym_close_arrow,
      anon_sym_DOT,
  [1258] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(42), 1,
      sym_comment,
    ACTIONS(169), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_close_bracket,
      sym_close_arrow,
      sym_identifier,
  [1275] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(43), 1,
      sym_comment,
    ACTIONS(185), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_close_bracket,
      sym_close_arrow,
      sym_identifier,
  [1292] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(44), 1,
      sym_comment,
    ACTIONS(173), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_close_bracket,
      sym_close_arrow,
      sym_identifier,
  [1309] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(45), 1,
      sym_comment,
    ACTIONS(187), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_close_bracket,
      sym_close_arrow,
      sym_identifier,
  [1326] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(46), 1,
      sym_comment,
    ACTIONS(189), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_close_bracket,
      sym_close_arrow,
      sym_identifier,
  [1343] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(47), 1,
      sym_comment,
    ACTIONS(191), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_close_bracket,
      sym_close_arrow,
      sym_identifier,
  [1360] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(48), 1,
      sym_comment,
    ACTIONS(193), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_close_bracket,
      sym_close_arrow,
      sym_identifier,
  [1377] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(49), 1,
      sym_comment,
    ACTIONS(195), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_close_bracket,
      sym_close_arrow,
      sym_identifier,
  [1394] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(50), 1,
      sym_comment,
    ACTIONS(159), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_close_bracket,
      sym_close_arrow,
      sym_identifier,
  [1411] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(51), 1,
      sym_comment,
    ACTIONS(197), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_close_bracket,
      sym_close_arrow,
      sym_identifier,
  [1428] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(201), 1,
      sym_hex,
    STATE(52), 1,
      sym_comment,
    ACTIONS(199), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      sym_close_bracket,
      sym_close_arrow,
      sym_identifier,
  [1447] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(53), 1,
      sym_comment,
    ACTIONS(203), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_close_bracket,
      sym_close_arrow,
      sym_identifier,
  [1464] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(54), 1,
      sym_comment,
    ACTIONS(205), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_close_bracket,
      sym_close_arrow,
      sym_identifier,
  [1481] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(55), 1,
      sym_comment,
    ACTIONS(207), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_close_bracket,
      sym_close_arrow,
      sym_identifier,
  [1498] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(56), 1,
      sym_comment,
    ACTIONS(209), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_close_bracket,
      sym_close_arrow,
      sym_identifier,
  [1515] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(57), 1,
      sym_comment,
    ACTIONS(211), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_close_bracket,
      sym_close_arrow,
      sym_identifier,
  [1532] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(58), 1,
      sym_comment,
    ACTIONS(213), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      sym_close_bracket,
      sym_close_arrow,
      sym_identifier,
  [1548] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(59), 1,
      sym_comment,
    ACTIONS(217), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
    ACTIONS(215), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_close_bracket,
      sym_close_arrow,
      sym_identifier,
  [1566] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(60), 1,
      sym_comment,
    ACTIONS(219), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      sym_close_bracket,
      sym_close_arrow,
      sym_identifier,
  [1582] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(141), 1,
      sym_oct,
    STATE(61), 1,
      sym_comment,
    ACTIONS(221), 2,
      anon_sym_X,
      anon_sym_x,
    ACTIONS(137), 4,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
      aux_sym_exp_token1,
  [1602] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(62), 1,
      sym_comment,
    ACTIONS(223), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      sym_close_bracket,
      sym_close_arrow,
      sym_identifier,
  [1618] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(63), 1,
      sym_comment,
    ACTIONS(227), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
    ACTIONS(225), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_close_bracket,
      sym_close_arrow,
      sym_identifier,
  [1636] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(64), 1,
      sym_comment,
    ACTIONS(231), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
    ACTIONS(229), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_close_bracket,
      sym_close_arrow,
      sym_identifier,
  [1654] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(65), 1,
      sym_comment,
    ACTIONS(213), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      sym_close_bracket,
      sym_close_arrow,
      sym_identifier,
  [1670] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(66), 1,
      sym_comment,
    ACTIONS(233), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      sym_close_bracket,
      sym_close_arrow,
      sym_identifier,
  [1686] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(67), 1,
      sym_comment,
    ACTIONS(235), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      sym_close_bracket,
      sym_close_arrow,
      sym_identifier,
  [1702] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(13), 1,
      sym_open_bracket,
    ACTIONS(15), 1,
      sym_open_arrow,
    ACTIONS(237), 1,
      anon_sym_COLON,
    ACTIONS(239), 1,
      anon_sym_LBRACK,
    STATE(68), 1,
      sym_comment,
    STATE(59), 2,
      sym_message_value,
      sym_message_list,
  [1725] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(69), 1,
      sym_comment,
    ACTIONS(241), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_close_bracket,
      sym_close_arrow,
      sym_identifier,
  [1739] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(243), 2,
      anon_sym_RBRACK,
      anon_sym_SLASH,
    ACTIONS(245), 2,
      anon_sym_DOT,
      sym_identifier,
    STATE(70), 2,
      sym_comment,
      aux_sym_type_name_repeat1,
  [1755] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(71), 1,
      sym_comment,
    ACTIONS(225), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_close_bracket,
      sym_close_arrow,
      sym_identifier,
  [1769] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(72), 1,
      sym_comment,
    ACTIONS(248), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_close_bracket,
      sym_close_arrow,
      sym_identifier,
  [1783] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(250), 1,
      anon_sym_RBRACK,
    ACTIONS(252), 1,
      anon_sym_SLASH,
    STATE(70), 1,
      aux_sym_type_name_repeat1,
    STATE(73), 1,
      sym_comment,
    ACTIONS(254), 2,
      anon_sym_DOT,
      sym_identifier,
  [1803] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(256), 1,
      anon_sym_DOT,
    ACTIONS(258), 1,
      aux_sym_exp_token1,
    STATE(44), 1,
      sym_exp,
    STATE(74), 1,
      sym_comment,
    ACTIONS(159), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1823] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(260), 1,
      aux_sym_dec_int_token2,
    STATE(75), 1,
      sym_comment,
    ACTIONS(137), 4,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
      aux_sym_exp_token1,
  [1839] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(262), 1,
      anon_sym_RBRACK,
    ACTIONS(264), 1,
      anon_sym_SLASH,
    STATE(73), 1,
      aux_sym_type_name_repeat1,
    STATE(76), 1,
      sym_comment,
    ACTIONS(254), 2,
      anon_sym_DOT,
      sym_identifier,
  [1859] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(77), 1,
      sym_comment,
    ACTIONS(266), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_close_bracket,
      sym_close_arrow,
      sym_identifier,
  [1873] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(78), 1,
      sym_comment,
    ACTIONS(268), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_close_bracket,
      sym_close_arrow,
      sym_identifier,
  [1887] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(262), 1,
      anon_sym_RBRACK,
    STATE(79), 1,
      sym_comment,
    STATE(87), 1,
      aux_sym_type_name_repeat1,
    ACTIONS(254), 2,
      anon_sym_DOT,
      sym_identifier,
  [1904] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(80), 1,
      sym_comment,
    ACTIONS(181), 4,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
      aux_sym_exp_token1,
  [1917] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(81), 1,
      sym_comment,
    ACTIONS(270), 4,
      anon_sym_COLON,
      anon_sym_LBRACK,
      sym_open_bracket,
      sym_open_arrow,
  [1930] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(258), 1,
      aux_sym_exp_token1,
    STATE(42), 1,
      sym_exp,
    STATE(82), 1,
      sym_comment,
    ACTIONS(173), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1947] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(83), 1,
      sym_comment,
    ACTIONS(272), 4,
      anon_sym_COLON,
      anon_sym_LBRACK,
      sym_open_bracket,
      sym_open_arrow,
  [1960] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(84), 1,
      sym_comment,
    ACTIONS(274), 4,
      anon_sym_RBRACK,
      anon_sym_SLASH,
      anon_sym_DOT,
      sym_identifier,
  [1973] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(13), 1,
      sym_open_bracket,
    ACTIONS(15), 1,
      sym_open_arrow,
    ACTIONS(276), 1,
      anon_sym_RBRACK,
    STATE(85), 1,
      sym_comment,
    STATE(94), 1,
      sym_message_value,
  [1992] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(258), 1,
      aux_sym_exp_token1,
    STATE(47), 1,
      sym_exp,
    STATE(86), 1,
      sym_comment,
    ACTIONS(169), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [2009] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(250), 1,
      anon_sym_RBRACK,
    STATE(70), 1,
      aux_sym_type_name_repeat1,
    STATE(87), 1,
      sym_comment,
    ACTIONS(254), 2,
      anon_sym_DOT,
      sym_identifier,
  [2026] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(88), 1,
      sym_comment,
    ACTIONS(278), 4,
      anon_sym_COLON,
      anon_sym_LBRACK,
      sym_open_bracket,
      sym_open_arrow,
  [2039] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(13), 1,
      sym_open_bracket,
    ACTIONS(15), 1,
      sym_open_arrow,
    STATE(89), 1,
      sym_comment,
    STATE(98), 1,
      sym_message_value,
  [2055] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(280), 1,
      anon_sym_COMMA,
    ACTIONS(283), 1,
      anon_sym_RBRACK,
    STATE(90), 2,
      sym_comment,
      aux_sym_message_list_repeat1,
  [2069] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(285), 1,
      sym_identifier,
    STATE(91), 1,
      sym_comment,
    STATE(102), 1,
      sym_type_name,
    STATE(117), 1,
      sym_domain,
  [2085] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(287), 1,
      anon_sym_COMMA,
    ACTIONS(290), 1,
      anon_sym_RBRACK,
    STATE(92), 2,
      sym_comment,
      aux_sym_scalar_list_repeat1,
  [2099] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(292), 1,
      sym_hex,
    STATE(93), 1,
      sym_comment,
    ACTIONS(199), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [2113] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(294), 1,
      anon_sym_COMMA,
    ACTIONS(296), 1,
      anon_sym_RBRACK,
    STATE(94), 1,
      sym_comment,
    STATE(97), 1,
      aux_sym_message_list_repeat1,
  [2129] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(298), 1,
      anon_sym_COMMA,
    ACTIONS(300), 1,
      anon_sym_RBRACK,
    STATE(95), 1,
      sym_comment,
    STATE(96), 1,
      aux_sym_scalar_list_repeat1,
  [2145] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(298), 1,
      anon_sym_COMMA,
    ACTIONS(302), 1,
      anon_sym_RBRACK,
    STATE(92), 1,
      aux_sym_scalar_list_repeat1,
    STATE(96), 1,
      sym_comment,
  [2161] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(294), 1,
      anon_sym_COMMA,
    ACTIONS(304), 1,
      anon_sym_RBRACK,
    STATE(90), 1,
      aux_sym_message_list_repeat1,
    STATE(97), 1,
      sym_comment,
  [2177] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(98), 1,
      sym_comment,
    ACTIONS(283), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [2188] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(99), 1,
      sym_comment,
    ACTIONS(290), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [2199] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(306), 1,
      sym_identifier,
    STATE(100), 1,
      sym_comment,
    STATE(101), 1,
      sym_type_name,
  [2212] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(308), 1,
      anon_sym_RBRACK,
    STATE(101), 1,
      sym_comment,
  [2222] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(310), 1,
      anon_sym_RBRACK,
    STATE(102), 1,
      sym_comment,
  [2232] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(312), 1,
      sym_hex,
    STATE(103), 1,
      sym_comment,
  [2242] = 3,
    ACTIONS(47), 1,
      anon_sym_POUND,
    ACTIONS(314), 1,
      aux_sym_comment_token1,
    STATE(104), 1,
      sym_comment,
  [2252] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(316), 1,
      sym_hex,
    STATE(105), 1,
      sym_comment,
  [2262] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(318), 1,
      sym_hex,
    STATE(106), 1,
      sym_comment,
  [2272] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(320), 1,
      sym_hex,
    STATE(107), 1,
      sym_comment,
  [2282] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(322), 1,
      sym_hex,
    STATE(108), 1,
      sym_comment,
  [2292] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(324), 1,
      sym_hex,
    STATE(109), 1,
      sym_comment,
  [2302] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(326), 1,
      sym_oct,
    STATE(110), 1,
      sym_comment,
  [2312] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(328), 1,
      aux_sym_dec_int_token2,
    STATE(111), 1,
      sym_comment,
  [2322] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(330), 1,
      aux_sym_dec_int_token2,
    STATE(112), 1,
      sym_comment,
  [2332] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(332), 1,
      sym_hex,
    STATE(113), 1,
      sym_comment,
  [2342] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(334), 1,
      aux_sym_dec_int_token2,
    STATE(114), 1,
      sym_comment,
  [2352] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(336), 1,
      sym_hex,
    STATE(115), 1,
      sym_comment,
  [2362] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(338), 1,
      sym_hex,
    STATE(116), 1,
      sym_comment,
  [2372] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(340), 1,
      anon_sym_SLASH,
    STATE(117), 1,
      sym_comment,
  [2382] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(342), 1,
      sym_hex,
    STATE(118), 1,
      sym_comment,
  [2392] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(344), 1,
      sym_hex,
    STATE(119), 1,
      sym_comment,
  [2402] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(346), 1,
      ts_builtin_sym_end,
    STATE(120), 1,
      sym_comment,
  [2412] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(348), 1,
      sym_hex,
    STATE(121), 1,
      sym_comment,
  [2422] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(350), 1,
      aux_sym_dec_int_token2,
    STATE(122), 1,
      sym_comment,
  [2432] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(352), 1,
      sym_oct,
    STATE(123), 1,
      sym_comment,
  [2442] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(354), 1,
      sym_hex,
    STATE(124), 1,
      sym_comment,
  [2452] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(356), 1,
      sym_hex,
    STATE(125), 1,
      sym_comment,
  [2462] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(358), 1,
      aux_sym_dec_int_token2,
    STATE(126), 1,
      sym_comment,
  [2472] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(360), 1,
      sym_hex,
    STATE(127), 1,
      sym_comment,
  [2482] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(362), 1,
      sym_hex,
    STATE(128), 1,
      sym_comment,
  [2492] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(364), 1,
      sym_hex,
    STATE(129), 1,
      sym_comment,
  [2502] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(366), 1,
      sym_hex,
    STATE(130), 1,
      sym_comment,
  [2512] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(368), 1,
      sym_hex,
    STATE(131), 1,
      sym_comment,
  [2522] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(370), 1,
      sym_hex,
    STATE(132), 1,
      sym_comment,
  [2532] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(372), 1,
      sym_hex,
    STATE(133), 1,
      sym_comment,
  [2542] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(374), 1,
      sym_hex,
    STATE(134), 1,
      sym_comment,
  [2552] = 1,
    ACTIONS(376), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 55,
  [SMALL_STATE(4)] = 97,
  [SMALL_STATE(5)] = 141,
  [SMALL_STATE(6)] = 185,
  [SMALL_STATE(7)] = 229,
  [SMALL_STATE(8)] = 273,
  [SMALL_STATE(9)] = 315,
  [SMALL_STATE(10)] = 344,
  [SMALL_STATE(11)] = 373,
  [SMALL_STATE(12)] = 402,
  [SMALL_STATE(13)] = 431,
  [SMALL_STATE(14)] = 484,
  [SMALL_STATE(15)] = 513,
  [SMALL_STATE(16)] = 542,
  [SMALL_STATE(17)] = 568,
  [SMALL_STATE(18)] = 594,
  [SMALL_STATE(19)] = 620,
  [SMALL_STATE(20)] = 646,
  [SMALL_STATE(21)] = 672,
  [SMALL_STATE(22)] = 698,
  [SMALL_STATE(23)] = 724,
  [SMALL_STATE(24)] = 750,
  [SMALL_STATE(25)] = 776,
  [SMALL_STATE(26)] = 802,
  [SMALL_STATE(27)] = 828,
  [SMALL_STATE(28)] = 854,
  [SMALL_STATE(29)] = 895,
  [SMALL_STATE(30)] = 922,
  [SMALL_STATE(31)] = 955,
  [SMALL_STATE(32)] = 988,
  [SMALL_STATE(33)] = 1021,
  [SMALL_STATE(34)] = 1054,
  [SMALL_STATE(35)] = 1087,
  [SMALL_STATE(36)] = 1114,
  [SMALL_STATE(37)] = 1137,
  [SMALL_STATE(38)] = 1170,
  [SMALL_STATE(39)] = 1194,
  [SMALL_STATE(40)] = 1218,
  [SMALL_STATE(41)] = 1238,
  [SMALL_STATE(42)] = 1258,
  [SMALL_STATE(43)] = 1275,
  [SMALL_STATE(44)] = 1292,
  [SMALL_STATE(45)] = 1309,
  [SMALL_STATE(46)] = 1326,
  [SMALL_STATE(47)] = 1343,
  [SMALL_STATE(48)] = 1360,
  [SMALL_STATE(49)] = 1377,
  [SMALL_STATE(50)] = 1394,
  [SMALL_STATE(51)] = 1411,
  [SMALL_STATE(52)] = 1428,
  [SMALL_STATE(53)] = 1447,
  [SMALL_STATE(54)] = 1464,
  [SMALL_STATE(55)] = 1481,
  [SMALL_STATE(56)] = 1498,
  [SMALL_STATE(57)] = 1515,
  [SMALL_STATE(58)] = 1532,
  [SMALL_STATE(59)] = 1548,
  [SMALL_STATE(60)] = 1566,
  [SMALL_STATE(61)] = 1582,
  [SMALL_STATE(62)] = 1602,
  [SMALL_STATE(63)] = 1618,
  [SMALL_STATE(64)] = 1636,
  [SMALL_STATE(65)] = 1654,
  [SMALL_STATE(66)] = 1670,
  [SMALL_STATE(67)] = 1686,
  [SMALL_STATE(68)] = 1702,
  [SMALL_STATE(69)] = 1725,
  [SMALL_STATE(70)] = 1739,
  [SMALL_STATE(71)] = 1755,
  [SMALL_STATE(72)] = 1769,
  [SMALL_STATE(73)] = 1783,
  [SMALL_STATE(74)] = 1803,
  [SMALL_STATE(75)] = 1823,
  [SMALL_STATE(76)] = 1839,
  [SMALL_STATE(77)] = 1859,
  [SMALL_STATE(78)] = 1873,
  [SMALL_STATE(79)] = 1887,
  [SMALL_STATE(80)] = 1904,
  [SMALL_STATE(81)] = 1917,
  [SMALL_STATE(82)] = 1930,
  [SMALL_STATE(83)] = 1947,
  [SMALL_STATE(84)] = 1960,
  [SMALL_STATE(85)] = 1973,
  [SMALL_STATE(86)] = 1992,
  [SMALL_STATE(87)] = 2009,
  [SMALL_STATE(88)] = 2026,
  [SMALL_STATE(89)] = 2039,
  [SMALL_STATE(90)] = 2055,
  [SMALL_STATE(91)] = 2069,
  [SMALL_STATE(92)] = 2085,
  [SMALL_STATE(93)] = 2099,
  [SMALL_STATE(94)] = 2113,
  [SMALL_STATE(95)] = 2129,
  [SMALL_STATE(96)] = 2145,
  [SMALL_STATE(97)] = 2161,
  [SMALL_STATE(98)] = 2177,
  [SMALL_STATE(99)] = 2188,
  [SMALL_STATE(100)] = 2199,
  [SMALL_STATE(101)] = 2212,
  [SMALL_STATE(102)] = 2222,
  [SMALL_STATE(103)] = 2232,
  [SMALL_STATE(104)] = 2242,
  [SMALL_STATE(105)] = 2252,
  [SMALL_STATE(106)] = 2262,
  [SMALL_STATE(107)] = 2272,
  [SMALL_STATE(108)] = 2282,
  [SMALL_STATE(109)] = 2292,
  [SMALL_STATE(110)] = 2302,
  [SMALL_STATE(111)] = 2312,
  [SMALL_STATE(112)] = 2322,
  [SMALL_STATE(113)] = 2332,
  [SMALL_STATE(114)] = 2342,
  [SMALL_STATE(115)] = 2352,
  [SMALL_STATE(116)] = 2362,
  [SMALL_STATE(117)] = 2372,
  [SMALL_STATE(118)] = 2382,
  [SMALL_STATE(119)] = 2392,
  [SMALL_STATE(120)] = 2402,
  [SMALL_STATE(121)] = 2412,
  [SMALL_STATE(122)] = 2422,
  [SMALL_STATE(123)] = 2432,
  [SMALL_STATE(124)] = 2442,
  [SMALL_STATE(125)] = 2452,
  [SMALL_STATE(126)] = 2462,
  [SMALL_STATE(127)] = 2472,
  [SMALL_STATE(128)] = 2482,
  [SMALL_STATE(129)] = 2492,
  [SMALL_STATE(130)] = 2502,
  [SMALL_STATE(131)] = 2512,
  [SMALL_STATE(132)] = 2522,
  [SMALL_STATE(133)] = 2532,
  [SMALL_STATE(134)] = 2542,
  [SMALL_STATE(135)] = 2552,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_double_string_repeat1, 2),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_double_string_repeat1, 2), SHIFT_REPEAT(24),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_double_string_repeat1, 2), SHIFT_REPEAT(18),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_double_string_repeat1, 2), SHIFT_REPEAT(123),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_double_string_repeat1, 2), SHIFT_REPEAT(124),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_double_string_repeat1, 2), SHIFT_REPEAT(133),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_double_string_repeat1, 2), SHIFT_REPEAT(119),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(123),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(124),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(133),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(119),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(110),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(109),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_single_string_repeat1, 2),
  [83] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_single_string_repeat1, 2), SHIFT_REPEAT(20),
  [86] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_single_string_repeat1, 2), SHIFT_REPEAT(19),
  [89] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_single_string_repeat1, 2), SHIFT_REPEAT(110),
  [92] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_single_string_repeat1, 2), SHIFT_REPEAT(109),
  [95] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_single_string_repeat1, 2), SHIFT_REPEAT(108),
  [98] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_single_string_repeat1, 2), SHIFT_REPEAT(107),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_escape, 2),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_escape, 3),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_escape, 4),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_escape, 1),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_single_string_repeat1, 1),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_escape, 6),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_double_string_repeat1, 1),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_escape, 5),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dec_int, 1),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dec_int, 1),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [147] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(91),
  [150] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(81),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1),
  [165] = {.entry = {.count = 1, .reusable = false}}, SHIFT(112),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 3),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float, 3),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 2),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float, 2),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_oct_int, 2),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dec_int, 2),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dec_int, 2),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_value, 2),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_value, 3),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_string, 3),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 4),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_oct_int, 3),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_single_string, 2),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hex_int, 3),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_single_string, 3),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_string, 2),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exp, 2),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar_value, 1),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hex_int, 4),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_list, 2),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_field, 2),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar_list, 4),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_list, 4),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_field, 3),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar_field, 3),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_list, 3),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar_list, 3),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_field, 4),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_name_repeat1, 2),
  [245] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_name_repeat1, 2), SHIFT_REPEAT(84),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar_field, 4),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_name, 2),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_domain, 2),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_name, 1),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_domain, 1),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 1),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_name, 1),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extension_name, 3),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_name_repeat1, 1),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_any_name, 5),
  [280] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_message_list_repeat1, 2), SHIFT_REPEAT(89),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_message_list_repeat1, 2),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [287] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scalar_list_repeat1, 2), SHIFT_REPEAT(28),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_scalar_list_repeat1, 2),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [314] = {.entry = {.count = 1, .reusable = false}}, SHIFT(135),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [346] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [370] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [376] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_textproto(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
